Revert "Improve error handling in Telegram API calls in announce.yml"
This reverts commit 011d5c0320e20ee2d04a261947438873317cf4c6.

diff --git a/.github/workflows/announce.yml b/.github/workflows/announce.yml
--- a/.github/workflows/announce.yml
+++ b/.github/workflows/announce.yml
@@ -50,7 +50,8 @@ jobs:
             }' \
             https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage)
           if [ $(echo $RESPONSE | jq .ok) != "true" ]; then
-            exit "Error: $(echo $RESPONSE | jq .description)"
+            echo "Error: $(echo $RESPONSE | jq .description)"
+            exit 1
           fi
           echo "MESSAGE_ID=$(echo $RESPONSE | jq .result.message_id)" >> $GITHUB_ENV
       - name: Pin announce message
@@ -65,7 +66,8 @@ jobs:
             }' \
             https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/pinChatMessage)
           if [ $(echo $RESPONSE | jq .ok) != "true" ]; then
-            exit "Error: $(echo $RESPONSE | jq .description)"
+            echo "Error: $(echo $RESPONSE | jq .description)"
+            exit 1
           fi
       - name: Presence poll
         run: |
@@ -84,5 +86,6 @@ jobs:
             }' \
             https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendPoll)
           if [ $(echo $RESPONSE | jq .ok) != "true" ]; then
-            exit "Error: $(echo $RESPONSE | jq .description)"
+            echo "Error: $(echo $RESPONSE | jq .description)"
+            exit 1
           fi
